spring:
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
  datasource:
    driver-class-name: org.postgresql.Driver
    user-name: "postgres"
    password: "Max.2005"
    url: "jdbc:postgresql://localhost:5432/Diary"
    hikari:
      jdbc-url: "${spring.datasource.url}"
  data:
    jdbc:
      dialect: postgresql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/master.xml
server:
  port: 8091
jwt:
  secret: K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=
  expiration: 10000000  #милисекунды
  refresh-token-expiration: 1000

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    filter: true
    display-request-duration: true
    enabled: true     # Отключить для production (false)
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  cache:
    disabled: true    # Для разработки, чтобы всегда получать свежую документацию

# logging:
  # level:

  #  org.springframework.security: DEBUG
  #  org.hibernate.SQL: DEBUG
  #  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
